### ISSUE TITLE
ModuleNotFoundError: No module named 'setvoronoi'

### ISSUE THREAD

**Issue by StanleyWong96** [SwaySZ/PySetVoronoi#7]
Hello, 

I have encounter problem when following the instruction in PySetVoronoi.

When I run in the terminal: python3 testsp.py

It came up:
  File "testsp.py", line 4, in <module>
    import setvoronoi as sv
ModuleNotFoundError: No module named 'setvoronoi'

Is there a solution for this problem?

Thank you!

**Comment by SwaySZ** [comment]
> 

Hello Stanley,

The problem is on searching path of Python package (i.e., setvoronoi here). Please make sure the compiled library is under the searching path (e.g., PYTHONPATH). An easy way is to add the path of setvoronoi into your script. Check the first line in the examplified script and you need to change it to the proper path.
`sys.path.insert(1, '../../install/lib')`

-Shiwei

**Comment by StanleyWong96** [comment]
Hello!

Thank you for the fast reply!

I have put the "setvoronoi.cpython-39-darwin.so" file from the "/install/lib/" in a directory named "setvoronoi". Also, the searching path directly to the file. So, the code run now. 

I have other problem that I encountered. 

  File "testsp.py", line 7, in <module>
    mycf = sv.CellFactory() #establish a factory (class) to handle the computation
AttributeError: module 'setvoronoi' has no attribute 'CellFactory'

Is there something I'm doing it wrong?

Thank you!

**Comment by SwaySZ** [comment]
No need to create a directory named 'setvoronoi', which is confusing to Python. Python would regard this folder as a module. And of course, it does not have an attribute of CellFactory. In fact, you haven't pointed to the *.so file.

**Comment by SwaySZ** [comment]
I will close the issue cause's it's inactive.
